'use client'

import React, { useState, useEffect } from 'react'
import Navigation from '@/components/navigation/navigation'
import { Sparkles, Trees, CheckCircle, RefreshCw, AlertCircle } from 'lucide-react'

interface Recommendation {
  id: string
  title: string
  description: string
  savings: number
  difficulty: 'Easy' | 'Medium' | 'Hard'
  completed: boolean
}

export default function AIInsightsPage() {
  const [recommendations, setRecommendations] = useState<Recommendation[]>([])
  const [loading, setLoading] = useState(true)
  const [regenerating, setRegenerating] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const fetchRecommendations = async (bypassCache = false) => {
    setError(null)
    if (bypassCache) {
      setRegenerating(true)
    } else {
      setLoading(true)
    }

    try {
      // For regeneration, we will delete uncompleted first or instruct API
      const res = await fetch('/api/recommendations')
      if (!res.ok) {
        throw new Error('Failed to load insights')
      }
      const data = await res.json()
      setRecommendations(data || [])
    } catch (err: any) {
      setError(err.message || 'Something went wrong')
    } finally {
      setLoading(false)
      setRegenerating(false)
    }
  }

  useEffect(() => {
    fetchRecommendations()
  }, [])

  const handleMarkCompleted = async (recId: string, currentStatus: boolean) => {
    try {
      // Optimistic UI update
      setRecommendations((prev) =>
        prev.map((rec) => (rec.id === recId ? { ...rec, completed: !currentStatus } : rec))
      )

      const res = await fetch('/api/recommendations', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          recommendationId: recId,
          completed: !currentStatus,
        }),
      })

      if (!res.ok) {
        throw new Error('Failed to update status')
      }
    } catch (err) {
      console.error(err)
      // Rollback on error
      setRecommendations((prev) =>
        prev.map((rec) => (rec.id === recId ? { ...rec, completed: currentStatus } : rec))
      )
      alert('Could not update recommendation status')
    }
  }

  const getDifficultyBadge = (level: 'Easy' | 'Medium' | 'Hard') => {
    switch (level) {
      case 'Easy':
        return 'text-emerald-600 bg-emerald-50 dark:bg-emerald-950/20 border-emerald-200 dark:border-emerald-900/50'
      case 'Medium':
        return 'text-amber-600 bg-amber-50 dark:bg-amber-950/20 border-amber-200 dark:border-amber-900/50'
      case 'Hard':
        return 'text-rose-600 bg-rose-50 dark:bg-rose-950/20 border-rose-200 dark:border-rose-900/50'
      default:
        return 'text-slate-600 bg-slate-50 border-slate-200'
    }
  }

  return (
    <div className="min-h-screen flex bg-slate-50 dark:bg-slate-950 pb-20 lg:pb-0">
      <Navigation />

      <main className="flex-1 lg:pl-64 min-h-screen p-4 sm:p-6 lg:p-8">
        <div className="max-w-4xl mx-auto space-y-6">
          {/* Header */}
          <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
            <div>
              <h1 className="text-2xl sm:text-3xl font-bold text-slate-800 dark:text-white font-display flex items-center gap-2">
                <Sparkles className="w-6 h-6 text-emerald-500 animate-pulse" />
                <span>AI Sustainability Insights</span>
              </h1>
              <p className="text-slate-500 dark:text-slate-400 mt-1 text-sm">
                Actionable climate recommendations generated by studying your recent habits.
              </p>
            </div>
            
            <button
              onClick={() => fetchRecommendations(true)}
              disabled={loading || regenerating}
              className="inline-flex items-center justify-center gap-2 px-4 py-2 border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 hover:bg-slate-50 dark:hover:bg-slate-850 text-slate-700 dark:text-slate-200 font-semibold rounded-xl transition-all text-xs cursor-pointer disabled:opacity-50"
            >
              <RefreshCw className={`w-3.5 h-3.5 ${regenerating ? 'animate-spin' : ''}`} />
              <span>Regenerate Recommendations</span>
            </button>
          </div>

          {error && (
            <div className="flex items-start gap-2 bg-rose-50 dark:bg-rose-950/20 border border-rose-200 dark:border-rose-900 text-rose-600 dark:text-rose-450 p-4 rounded-xl text-sm">
              <AlertCircle className="w-5 h-5 shrink-0 mt-0.5" />
              <span>{error}</span>
            </div>
          )}

          {loading ? (
            /* Skeleton Cards */
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              {[1, 2, 3].map((i) => (
                <div key={i} className="bg-white dark:bg-slate-900 border border-slate-250/20 dark:border-slate-800 rounded-2xl p-6 h-64 animate-pulse space-y-4">
                  <div className="h-4 w-12 bg-slate-200 dark:bg-slate-800 rounded" />
                  <div className="h-6 w-40 bg-slate-200 dark:bg-slate-800 rounded" />
                  <div className="h-16 w-full bg-slate-200 dark:bg-slate-800 rounded" />
                  <div className="h-10 w-full bg-slate-200 dark:bg-slate-800 rounded-xl" />
                </div>
              ))}
            </div>
          ) : recommendations.length === 0 ? (
            <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-12 text-center shadow-sm space-y-4">
              <div className="flex items-center justify-center w-16 h-16 mx-auto rounded-2xl bg-emerald-50 dark:bg-emerald-950/20 text-emerald-500">
                <Trees className="w-8 h-8" />
              </div>
              <div className="max-w-xs mx-auto space-y-2">
                <h2 className="text-lg font-bold text-slate-850 dark:text-white">No active recommendations</h2>
                <p className="text-slate-500 dark:text-slate-400 text-xs">
                  Once you log daily activities in the tracking tool, our AI engine will generate reduction tips.
                </p>
              </div>
            </div>
          ) : (
            /* Recommendation Grid */
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              {recommendations.map((rec) => (
                <div
                  key={rec.id}
                  className={`bg-white dark:bg-slate-900 border rounded-2xl p-6 shadow-sm flex flex-col justify-between transition-all ${
                    rec.completed
                      ? 'border-emerald-300 dark:border-emerald-800/80 bg-emerald-50/5 dark:bg-emerald-950/5 ring-1 ring-emerald-500/10'
                      : 'border-slate-200 dark:border-slate-800'
                  }`}
                >
                  <div className="space-y-4">
                    {/* Header: Difficulty & Savings */}
                    <div className="flex justify-between items-center">
                      <span className={`text-[10px] font-bold uppercase tracking-wider px-2 py-0.5 rounded-full border ${getDifficultyBadge(rec.difficulty)}`}>
                        {rec.difficulty}
                      </span>
                      <span className="text-[11px] font-bold text-emerald-600 dark:text-emerald-450 bg-emerald-50 dark:bg-emerald-950/30 px-2 py-0.5 rounded-md">
                        -{rec.savings} kg CO₂/mo
                      </span>
                    </div>

                    {/* Content */}
                    <div className="space-y-1.5">
                      <h3 className={`font-bold text-sm ${rec.completed ? 'text-slate-400 line-through dark:text-slate-500' : 'text-slate-850 dark:text-white'}`}>
                        {rec.title}
                      </h3>
                      <p className="text-xs text-slate-500 dark:text-slate-400 leading-relaxed">
                        {rec.description}
                      </p>
                    </div>
                  </div>

                  {/* Action Button */}
                  <button
                    onClick={() => handleMarkCompleted(rec.id, rec.completed)}
                    className={`w-full py-2.5 rounded-xl text-xs font-semibold mt-6 transition-all flex items-center justify-center gap-1.5 cursor-pointer ${
                      rec.completed
                        ? 'bg-emerald-50 text-emerald-600 border border-emerald-250 hover:bg-emerald-100 dark:bg-emerald-950/20 dark:text-emerald-400 dark:border-emerald-900/50'
                        : 'bg-slate-800 hover:bg-slate-900 text-white dark:bg-slate-800 dark:hover:bg-slate-750'
                    }`}
                  >
                    {rec.completed ? (
                      <>
                        <CheckCircle className="w-4 h-4 text-emerald-500 fill-emerald-500 dark:fill-transparent" />
                        <span>Completed</span>
                      </>
                    ) : (
                      <span>Mark as Completed</span>
                    )}
                  </button>
                </div>
              ))}
            </div>
          )}

          {/* Educational Note */}
          <div className="bg-slate-100/50 dark:bg-slate-900/40 border border-slate-200 dark:border-slate-850 p-5 rounded-2xl text-xs text-slate-500 dark:text-slate-400 space-y-2">
            <h4 className="font-bold text-slate-700 dark:text-slate-300">How recommendation savings are computed:</h4>
            <p className="leading-relaxed">
              Our AI analysis estimates carbon reduction potentials based on standard environmental datasets. Implementing these recommendations directly avoids greenhouse gases. Try to focus on "Easy" items first before challenging yourself with "Medium" or "Hard" routines!
            </p>
          </div>
        </div>
      </main>
    </div>
  )
}
